lang: 'it'
title: "DVRI - Distretto Veneziano della Ricerca e dell'Innovazione"
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap
enviroment: production
permalink: "/:title:output_ext"
url: "http://distrettovenezianoricerca.it"
exclude: [Gemfile,
          Gemfile.lock,
          node_modules,
          vendor/bundle/,
          vendor/cache/,
          vendor/gems/,
          vendor/ruby/,
          test/,
          LICENSE.txt,
          Rakefile,
          README.md]
