lang: 'it'
title: "DVRI - Distretto Veneziano della Ricerca e dell'Innovazione"
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap
enviroment: production
permalink: "/:title:output_ext"
url: "http://distrettovenezianoricerca.it"
# exclude: ['test', 'LICENSE.txt', 'Rakefile', 'README.md']
