lang: 'it'
title: "DVRI - Distretto Veneziano della Ricerca e dell'Innovazione"
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

defaults:
  - scope:
      path: assets/gallery/social_events_2018
    values:
      social_2018: true

enviroment: production
permalink: "/:title:output_ext"
url: "http://distrettovenezianoricerca.it"
exclude: [Gemfile,
          Gemfile.lock,
          node_modules,
          vendor/bundle/,
          vendor/cache/,
          vendor/gems/,
          vendor/ruby/,
          test/,
          LICENSE.txt,
          Rakefile,
          README.md]
