lang: 'it'
title: "DVRI - Distretto Veneziano della Ricerca e dell'Innovazione"
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap  
enviroment: production
permalink: "/:title.html"
url: "http://distrettovenezianoricerca.it/"
